### ISSUE TITLE
Missing file and conversion error

### ISSUE THREAD

**Issue by 4melts** [AllusiveWheat/skeet.pw#1]
Hello, 
From where do you include "Globals.h" and "Interfaces.h". Also im having this error
![image](https://user-images.githubusercontent.com/61282998/103466314-a8379400-4d4c-11eb-92c4-9b8e2191dd55.png)

**Comment by AllusiveWheat** [comment]
Hello
Do you have the Direct X 9 SDK installed also did you build with  Visual Studio 2017 build tools, and where did you see you needed to include those files?

**Comment by 4melts** [comment]
Yeah I have it included as well. I retargeted to Visual Studio 2019. I'll send the locations once I get on my pc.

**Comment by 4melts** [comment]
Either I can't find the skrt folder on your github or you removed it. There is a skrt folder when I downloaded a zip of your code and there is a imgui.cpp inside of it. The error is on line 5602.
The other one is in Menu.h line 2

**Comment by AllusiveWheat** [comment]
Oh ya I was  trying to  change the menu gave up for know just edited some things anyway  remove that folder

**Comment by 4melts** [comment]
Im still having the conversion issue tho.
![Uploading image.png…]()
 Sol.hpp

**Comment by AllusiveWheat** [comment]
I see lua seems to be your issue have you made sure to compile in vs 2017 release x86

**Comment by 4melts** [comment]
I compiled 2019 x86 release
