### ISSUE TITLE
Cant build new version

### ISSUE THREAD

**Issue by roccoishot** [AllusiveWheat/skeet.pw#10]
![image](https://user-images.githubusercontent.com/61354873/111788984-12b19800-8897-11eb-9bae-8219a3f0494d.png)
Tried also using skeet.pw build mode too.

**Comment by roccoishot** [comment]
I have visual studio 2015-2019 installed and directx sdk and I checked if they were updated

**Comment by AllusiveWheat** [comment]
Try again should work I fixed it

**Comment by leoireo** [comment]
I got 7600 errors :(

**Comment by Dufham2121** [comment]
https://prnt.sc/10ra05i

erorr lua.lib

**Comment by AllusiveWheat** [comment]
Fixed Added Lua.lib
