### ISSUE TITLE
Wont Compile

### ISSUE THREAD

**Issue by ClownK1NG** [AllusiveWheat/skeet.pw#13]
![image](https://user-images.githubusercontent.com/77850000/112153907-10777280-8be4-11eb-8d42-200fc9d4dc5b.png)

**Comment by ClownK1NG** [comment]
Those are the Errors i am getting

**Comment by saad977-ai** [comment]
**_Change Release to skeet.pw_**

**Comment by saad977-ai** [comment]
![image](https://user-images.githubusercontent.com/75268226/112265264-0ad96580-8c94-11eb-87a5-76b38aeba70a.png)

And Go to Project settings

![image](https://user-images.githubusercontent.com/75268226/112265353-2ba1bb00-8c94-11eb-8e50-4e10ffdd45b7.png)

![image](https://user-images.githubusercontent.com/75268226/112265440-4ffd9780-8c94-11eb-884f-1e19593d97bd.png)

**Comment by ClownK1NG** [comment]
Thanks that fixed it
