### ISSUE TITLE
Visual C++ Runtime error

### ISSUE THREAD

**Issue by misiekpl** [AllusiveWheat/skeet.pw#15]
I can't inject the cheat. I'm getting Visual C++ Runtime error.
CSGhost v3 injector

**Comment by AllusiveWheat** [comment]
Run CSGO  and CSGhost as admin and make sure you pull latest repo and build

**Comment by misiekpl** [comment]
Yeah, i used latest repo and build but still doesn't work.
I run injector as admin.
