### ISSUE TITLE
Crashes with Legitbot

### ISSUE THREAD

**Issue by AsukiiJapan** [AllusiveWheat/skeet.pw#16]
it crashed when i use psilent or manual aimbot when i set it on key 

Btw i love your cheat man you the best!<3333333

**Comment by AsukiiJapan** [comment]
can you add please more features? like aimbot Chams visuals? pleaseeee!

**Comment by AllusiveWheat** [comment]
Why? There already there and I have no idea why it is crashing anyway it is vac detected
