### ISSUE TITLE
wtf with tabs?

### ISSUE THREAD

**Issue by krupa637** [AllusiveWheat/skeet.pw#19]
![Снимок экрана (281)](https://user-images.githubusercontent.com/82304314/115980470-cb61aa00-a5ae-11eb-906e-56094fca4972.png)
![Снимок экрана (280)](https://user-images.githubusercontent.com/82304314/115980476-d9172f80-a5ae-11eb-8c5f-249a4e2de75e.png)

**Comment by RXVAN** [comment]
what?
