### ISSUE TITLE
Issue 01 : Crash on Injection

### ISSUE THREAD

**Issue by saad977-ai** [AllusiveWheat/skeet.pw#3]
![iasifasif](https://user-images.githubusercontent.com/75268226/109486271-791b7580-7aa4-11eb-8add-1344c0944e1a.png)

Getting this error on injection
 Can u tell me where is protection for dll so its crashing ?

**Comment by limo-p** [comment]
Have you tried debugging?

**Comment by saad977-ai** [comment]
No But i thought it is protected dll , any things special to debug here?

**Comment by limo-p** [comment]
It's not protected. What inject are you using try using csghost it has worked for me

**Comment by saad977-ai** [comment]
i have added you at discord accept my req at Saad#1594 ,, i used
csghost 3.1 injector it gives runtime error

**Comment by AllusiveWheat** [comment]
Use csghost 3.0 Thanks
