### ISSUE TITLE
Visual C++ Runtime error

### ISSUE THREAD

**Issue by Pelix7** [AllusiveWheat/skeet.pw#6]
![image](https://user-images.githubusercontent.com/80033274/109936947-1e1d9480-7cd7-11eb-9e02-957efa2a6e84.png)
Im getting this error every time i try to inject skeet.pw. I have tried many injectors (Csghost 2.6 3.0 3.1, Randoinjector and sazinjector) and I tried to reinstall my visual C++ drivers. Nothing worked so you have any ideas that would help?

**Comment by AllusiveWheat** [comment]
Create a skeet.pw folder in AppData 
C:\Users\Username\AppData\Roaming\skeet.pw

**Comment by Pelix7** [comment]
I had that folder in my roaming folder but I still keep getting that error.

**Comment by AllusiveWheat** [comment]
![Screenshot 2021-03-14 200610](https://user-images.githubusercontent.com/37462003/111098449-be0dc600-8500-11eb-9605-d6e29ad0e3f2.png)
Create These folders

**Comment by misiekpl** [comment]
Still same problem

**Comment by misiekpl** [comment]
> ![Screenshot 2021-03-14 200610](https://user-images.githubusercontent.com/37462003/111098449-be0dc600-8500-11eb-9605-d6e29ad0e3f2.png)
> Create These folders

This doesn't work for me
